### ISSUE TITLE
[FEATURE REQUEST]: simple trading view sell field max is confusing

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet-desktop#1289]
Right now we use max_taker_vol for call output in both mobile and desktop what can be confusing for the user since max amount is not equal his max balance (especially in case of really high fees such as for ETH), we should think on how to improve UX here

https://user-images.githubusercontent.com/24797699/133405008-deecee08-a3cc-4701-8f5f-5d1011fa7862.mov

**Comment by smk762** [comment]
Issue still exists. Tooltip seems pointless too if its the same as "tradable balance". Will try and find an easy fix for this tonight.

**Comment by smk762** [comment]
closing, tooltip added in #2288
