### ISSUE TITLE
Improve Combobox selectors

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet-desktop#1706]
- Overflow no longer visible, and ellipses visible in both light/dark
- We could improve this  with more linebreaks or "mouseover ticker shows fullname" & "mouseover balance shows fiat value", but will leave that for a future PR
![image](https://user-images.githubusercontent.com/35845239/160565905-442ea869-afeb-42f9-bba3-b1fc588b9511.png)
![image](https://user-images.githubusercontent.com/35845239/160565954-2cea2a80-5c77-4e75-bfe0-152b1daef090.png)

_Originally posted by @smk762 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1561#issuecomment-1081584942_

**Comment by cipig** [comment]
i have this in "Confirm Exchange Details":
![image](https://user-images.githubusercontent.com/32116761/161357453-00b47158-4c84-4e52-87ee-39d6b9f56b56.png)

and in swap details
![image](https://user-images.githubusercontent.com/32116761/161357501-6f9f2eb5-8909-45b9-95a0-d6d7426f7f29.png)

guess it's worth trying to use 3 separate lines for ticker, name and price in all this places

**Comment by SylEze** [comment]
> i have this in "Confirm Exchange Details": ![image](https://user-images.githubusercontent.com/32116761/161357453-00b47158-4c84-4e52-87ee-39d6b9f56b56.png)
> 
> and in swap details ![image](https://user-images.githubusercontent.com/32116761/161357501-6f9f2eb5-8909-45b9-95a0-d6d7426f7f29.png)
> 
> guess it's worth trying to use 3 separate lines for ticker, name and price in all this places

We should put this in another issue since there are not related to ticker selectors from pro trading view

**Comment by smk762** [comment]
closing as stale. Combo selectors have been improved
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/35845239/de64819f-5594-4d15-a1a1-878e9cbecc66)
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/35845239/9d84e3b0-45fe-4fa1-bcb3-40fce6463e71)
