### ISSUE TITLE
[FEATURE REQUEST]: add a shadow around the application border

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/komodo-wallet-desktop#1720]
It would be nice to add something like a shadow around the application window. Because it's hard to understand where the border is, and it's confusing.

Example:
![image](https://user-images.githubusercontent.com/77272165/161570931-5b07a32a-3097-4c0e-aea5-ee1f72649bfb.png)

**Comment by smk762** [comment]
closing as stale
