### ISSUE TITLE
[FEATURE REQUEST]: Make left sidebar animation less distracting when switching between different tabs

### ISSUE THREAD

**Issue by pbca26** [KomodoPlatform/komodo-wallet-desktop#1828]
**Is your feature request related to a problem? Please describe.**
Left sidebar on hover animation is a bit distracting when one needs to switch between tabs like Porfolio and Wallet

**Describe the solution you'd like**
Add either a toggle to sidebar to reveal/hide it on click or add an option to the settings in order to select appropriate behavior (e.g. fixed/animated)

**Describe alternatives you've considered**
I'm attaching a short screen capture session to demonstrate one possible solution

https://user-images.githubusercontent.com/7769879/176201263-5f7a2cad-8647-4832-be23-509b66a44abc.mov

https://user-images.githubusercontent.com/7769879/176201286-793abab6-ef9b-4f39-8744-4373f2a5a737.mov

**Comment by smk762** [comment]
related - https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1473

**Comment by smk762** [comment]
https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1962 was an option but was closed as imperfect. 
Ideally we would have our design team offer some feedback regarding the best solution. cc @tonymorony

**Comment by smk762** [comment]
closing as obsolete. sidebar is now static.
