### ISSUE TITLE
[FEATURE REQUEST]: Device time sync check/warning

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet-desktop#1857]
Sometimes users face errors due to an incorrect clock time on their computer.
If we could detect that and display a warning, it would help users avoid confusion.

**Comment by tonymorony** [comment]
needs https://github.com/KomodoPlatform/atomicDEX-API/issues/1115 to be implemented first

**Comment by smk762** [comment]
API is ready, and this has been implemented in web https://github.com/KomodoPlatform/komodo-wallet-archive/pull/1349
