### ISSUE TITLE
[FEATURE REQUEST]:  Add nomics graph to asset page

### ISSUE THREAD

**Issue by Liamrabbitt** [KomodoPlatform/komodo-wallet-desktop#1916]
[ADEX with Nomics Chart.pdf](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/9271509/ADEX.with.Nomics.Chart.pdf)
**Is your feature request related to a problem? Please describe.**
If no trade takes place in the last 10 min  no price is displayed. With chart added to each asset page you woul see a last price traded.

**Describe the solution you'd like**
Attched is a screen shoot of what it might look like.

**Describe alternatives you've considered**
Increase the time from 10 min to 24 hours or last trade

**Additional context**
Thats all
<img width="909" alt="ADEX with Nomics Chart" src="https://user-images.githubusercontent.com/70492736/183158217-2b5bfc76-27c7-4d6f-8201-80cc13ccd23b.png">

**Comment by smk762** [comment]
Closing, nomics is no more. Let poor one out :tumbler_glass:
