### ISSUE TITLE
[BUG]: Trying to send PEP fails to broadcast

### ISSUE THREAD

**Issue by Heclalava** [KomodoPlatform/komodo-wallet-desktop#2]
**Describe the bug**
Trying to send PEP from Linux AppImage to exchange

**To Reproduce**
1. Click Send
2. Fill out recipient details
3. Click proceed
4. Pop up with failed to broacast and long error code pops up

**Expected behavior**
Wallet completes the send transaction

**Operating Environment(s):**
 - OS: Linuc Mint
 - OS version: 22
 - Komodo Wallet Desktop Version: AppImage 0.8.0
 - Build branch: 
 - 
![image](https://github.com/user-attachments/assets/a51b80aa-af3c-401b-b511-bb4005ee787d)

**Additional context**
 - Error produced:
 
[error.txt](https://github.com/user-attachments/files/17528458/error.txt)

**Comment by Heclalava** [comment]
Seems like it tried to broadcast to a bad Electrum server, should it not fallback to another good server in this situation? i.e. so round robin through the Electrum servers list until the broadcast is successful?

**Comment by Heclalava** [comment]
Ok so it wasn't an issue with the Electrum servers but because the transaction was over 100kb in size. 

I managed to resolve the issue by using coin control features in the Pepecoin core wallet linked to in this feature request

https://github.com/KomodoPlatform/komodo-wallet/issues/2487

I was able to consolidate all the utxo inputs into one input using this feature.

**Comment by cipig** [comment]
the size of a tx is limited by various factors... the number of inputs is limited by coin daemon... the size is also limited, eg by electrumx itself... in electrumx you can change the setting by setting `MAX_SEND`, see https://electrumx-spesmilo.readthedocs.io/en/latest/environment.html#envvar-MAX_SEND ... i use `MAX_SEND = 2000000`, default is 1M

but i would recommend to not produce millions of tiny UTXOs in the first place, eg by changing min_payout of the pool... no need to produce 100 payouts per pay, one payout per day is enough

**Comment by cipig** [comment]
it's also possible to consolidate those UTXOs automatically... i use this for KMD `\"utxo_merge_params\":{\"merge_at\":200,\"check_every\":600,\"max_merge_at_once\":100}`... checks every 10 minutes if number of UTXOs is > 200 and if it's the case it merges 100 of them into 1... just need to be added to the GUIs... there was an issue about that, but they were all closed... only the one in coins repo is left: https://github.com/KomodoPlatform/coins/issues/705

**Comment by smk762** [comment]
Closing as cause of issue identified and problem solved.
