### ISSUE TITLE
[FR]: visualise my orders in the orderbook

### ISSUE THREAD

**Issue by ca333** [KomodoPlatform/komodo-wallet-desktop#2120]
in the order-book view hint/visualise my orders (e.g. colour tag/label/highlight, dot/icon, et cetera) so its clearly/easily visible to me. (check CEX UIs for example - all do it same/similar way)

**Comment by smk762** [comment]
Currently in pro view, the orderbook will include a small dot to the right of any rows which are the user's own orders. 
![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/35845239/290168d5-344a-438e-a15b-9f78a7758100)

@ca333 please advise if further visualisation is required, else close issue.

**Comment by smk762** [comment]
closing as stale
