### ISSUE TITLE
[FR]: Turkish translations update

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet-desktop#2137]
Since the last time translations were updated, a variety of elements have been changed or updated which now display as English in the app when user has set language to Turkish.

When we encounter these elements, we can post in this issue for @ozkanonur and @caglaryucekaya to provide updated translations.

**Comment by ozkanonur** [comment]
feel free to ping me - needed to drop the assignee for clearing up my assigned issue list
