### ISSUE TITLE
ARRR / ARRR Activation Failed... Zcash Params sit at 0%

### ISSUE THREAD

**Issue by moreWax** [KomodoPlatform/komodo-wallet-desktop#2189]
I have been trying to add ARRR to my portfolio but I need to download the params but they just sit at 0%.

Is there any way to download the zcash params externally and then import?

**Comment by cipig** [comment]
You can download with https://github.com/KomodoPlatform/komodo/blob/master/zcutil/fetch-params.sh
or https://github.com/KomodoPlatform/komodo/blob/master/zcutil/fetch-params.bat, depending on your OS.

**Comment by smk762** [comment]
closing issue as stale. please reopen if you still have the issue, or join our discord for support.
