### ISSUE TITLE
[BUG]: High font contrast when sending form Address Book

### ISSUE THREAD

**Issue by endrilickollari** [KomodoPlatform/komodo-wallet-desktop#2309]
When the user wants to send from the Address Book, address text contrast needs to be fixed, in dark mode basically can't see anything, also in light mode is between gray and white. 

![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/32954585/21886330-3afd-4f4d-9488-44a40c48cac6)

![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/32954585/89e2079f-f6da-4b39-9de6-926a24884cde)

**Operating Environment(s):**
 - OS: Windows
 - OS version: 10
 - AtomicDEX Version: 0.5.8

**Comment by smk762** [comment]
closing, issue no longer present in recent dev builds
