### ISSUE TITLE
[FR]: Add message while searching for addresses (no result)

### ISSUE THREAD

**Issue by endrilickollari** [KomodoPlatform/komodo-wallet-desktop#2312]
When searching the address book, and there is no data, I think to show a message that there is no address with a specified query, something like this, because leaving it empty would leave users confused. Either is an error or there is no data.

![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/32954585/8bfd6b2e-18e2-466c-9034-bf3e01ee4e33)

**Comment by smk762** [comment]
Issue has been resolved
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/35845239/4bd2e224-a394-4ac2-b4fa-a238bf0cf677)
