### ISSUE TITLE
[BUG]: mm2 crash

### ISSUE THREAD

**Issue by ciumete** [KomodoPlatform/komodo-wallet-desktop#2317]
**To Reproduce**
1. Go to 'Run Atomicdex Desktop ver 0.5.8'
2. After few seconds mm2.exe crush

**Operating Environment(s):**
 - OS: Windows
 - OS version: 10
 - AtomicDEX Version: 0.5.8]

Log file :

29 17:26:27, atomicdex_gossipsub::behaviour:189] INFO Subscribed to topic: orbk/LBC:THC
29 17:26:27, coins::utxo::utxo_builder::utxo_coin_builder:820] INFO Use protocol version 1.4 for Electrum "electrum25.groestlcoin.org:50001"
29 17:26:27, common:500] panicked at 'index out of bounds: the len is 2 but the index is 2', mm2src\coins\utxo\utxo_common.rs:3119:29
29 17:26:27, common:501] backtrace
  ??:0] BaseThreadInitThunk 0x7ffbba647613
  ??:0] RtlUserThreadStart 0x7ffbba7826f0

![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/4376271/fb19f04c-4808-4b10-94f1-dcfc438f3d2d)

**Comment by tonymorony** [comment]
thank you for issue opening! 

@shamardy could please someone from API team investigate why this crash might happen / can it be actual?
`29 17:26:27, common:500] panicked at 'index out of bounds: the len is 2 but the index is 2', mm2src\coins\utxo\utxo_common.rs:3119:29`

**Comment by ciumete** [comment]
> thank you for issue opening!
> 
> @shamardy could please someone from API team investigate why this crash might happen / can it be actual? `29 17:26:27, common:500] panicked at 'index out of bounds: the len is 2 but the index is 2', mm2src\coins\utxo\utxo_common.rs:3119:29`

is still actual, same error

**Comment by shamardy** [comment]
> could please someone from API team investigate why this crash might happen / can it be actual?

This is related to tx history, this can happen if there is a problem with transaction deserialization. It would be good to know which coin and transaction produced this error but this info are not in the logs. I will transfer this issue to the komodefi repo.

**Comment by shamardy** [comment]
@tonymorony Opened an issue in the related repo https://github.com/KomodoPlatform/komodo-defi-framework/issues/1906

**Comment by shamardy** [comment]
The PR that fixes this will be in the next API release, once this release is in desktop we can know more about the coin/transactions from the wallet history that caused this problem through the logs. Mm2 will not crash while starting then but some transactions will not be shown in history due to the problem we are trying to pinpoint.

**Comment by smk762** [comment]
Test builds for this bug at https://github.com/KomodoPlatform/komodo-wallet-desktop/actions/runs/5876114420

**Comment by smk762** [comment]
Closing - Fixed in API which will be in next version of app.
