### ISSUE TITLE
[FR]: Please add USDT-TRC20 wallet

### ISSUE THREAD

**Issue by johndoanee** [KomodoPlatform/komodo-wallet-desktop#2337]
**Is your feature request related to a problem? Please describe.**
I used this wallet in linux, but i can not add a USDT-TRC20 wallet.

**Describe your solution**
Could you please add Tether(TRC20) wallet feature to this wallet?
Thanks!

**Comment by cipig** [comment]
TRC20 is not supported yet
see https://github.com/KomodoPlatform/komodo-defi-framework/issues/1542

**Comment by smk762** [comment]
Closing - this is an issue for the repo Cipi mentioned. Once supported there, it will appear in the app.
