### ISSUE TITLE
[BUG]: DEX pro cuts off with expanded sidebar

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet-desktop#2345]
**Describe the bug**
Just look

![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/35845239/773053a6-86b7-4a46-a512-016e5257648f)

**To Reproduce**
1. Login
2. Go to dex page
3. Just look
4. See it

**Expected behavior**
  no cut off

**Operating Environment(s):**
 - Build branch: dev https://github.com/KomodoPlatform/komodo-wallet-desktop/commit/beaa7ec1c0187a6cafee5b1db0d6f79ec006bf80

**Additional context**
 - Regression after merging https://github.com/KomodoPlatform/komodo-wallet-desktop/pull/2334

**Comment by cipig** [comment]
maybe increase min resolution https://github.com/KomodoPlatform/komodo-wallet-desktop/issues/2243 (eg to 1366x768 from 1280x800) and make the window wider... the increased resolution actually covers more cases then the current one
