### ISSUE TITLE
[CI] Cant run app. Apple cannot check for Malicious software  warning appeared.

### ISSUE THREAD

**Issue by kivqa** [KomodoPlatform/komodo-wallet-desktop#2358]
Legacy app could not be run. Apple cannot check for Malicious software  warning appeared.
Please give us a clear and concise description of what the bug is, including screenshots or video if applicable.

![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/130828357/c0ca6f50-900b-41a3-9720-a86eda931266)

**To Reproduce**
1. Download release app for macos in PR #2352
2. Install and try to run

**Expected behavior**
App runs with out Malicious software  warning

**Operating Environment(s):**
 - OS: MacOS 13.4.1

 - Build branch:  enhance-fiat-select

**Comment by smk762** [comment]
We need to rotate developer certs in the CI, and update to use `notarytool`. Leaving this link here for reference: https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/

**Comment by kivqa** [comment]
issue is not reproducible
