### ISSUE TITLE
[BUG]: DOC/MARTY pair does not have orders on Simple DEX view

### ISSUE THREAD

**Issue by kivqa** [KomodoPlatform/komodo-wallet-desktop#2369]
**Describe the bug**
DOC/MARTY pair does not have orders on Simple DEX view. On PRO view orders work as expected for this pair

**To Reproduce**
<img width="754" alt="image" src="https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/130828357/9fb639ab-7acd-453c-9889-0ab2b61ae551">

**Operating Environment(s):**
 - Komodo Wallet Version:  0.6.1-beta

**Comment by smk762** [comment]
I've had a look for the root cause of this issue but it escapes me. Will try again after next release.

**Comment by smk762** [comment]
confirming this is not due to bestorders response for testcoins, so it must be in the code. I believe this may have been intentional to avoid users buying testcoins for real coins, but this would be better achieved with icons or warnings to indicate testcoins rather than omit them

**Comment by cipig** [comment]
take a look here: https://github.com/KomodoPlatform/komodo-wallet-desktop/blob/dev/src/core/atomicdex/models/qt.orderbook.proxy.model.cpp#L170
orders are removed if the coin does not have 10k volume... and some other things

**Comment by smk762** [comment]
> take a look here: https://github.com/KomodoPlatform/komodo-wallet-desktop/blob/dev/src/core/atomicdex/models/qt.orderbook.proxy.model.cpp#L170 orders are removed if the coin does not have 10k volume... and some other things

conditional is `if (is_cex_id_available && (rates > 100 || fiat_price <= 0 || ((safe_float(volume) < limit) && coin_info.coin_type != CoinType::SmartChain)))`

For DOC/MARTY, `is_cex_id_available` is false and they are coin_type smartchain, so this should not trigger it.
