### ISSUE TITLE
[BUG]: wrong price of 0 is shown on Portfolio page

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/komodo-wallet-desktop#2408]
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/32116761/f9e58364-dfa2-4315-b8e4-471265ab694b)

Komodo Wallet shows a price of 0 (with 8 decimals) for CHTA as coming from livecoinwatch, but the price from our endpoint on https://prices.komodo.earth/api/v2/tickers?expire_at=21600 is 0.000001 (6 decimals):

![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/32116761/1a1cc8f0-bc1f-4969-a6cb-ecee68d4f25c)

Interesting is that the price is actually used, else there wouldn't be a "Fiat Balance" value.

**Comment by ShorelineCrypto** [comment]
Not exactly the same, but likely came from same source of error of pricing. For pytomicDEX_makebot I did over past couple of days, I found this error and bot won't run on CHTA/KMD pairs:
ERROR simple_market_maker:372] Rates from provider are Unknown - skipping for KMD/CHTA 

The error came from here from mm2 code:
 https://github.com/KomodoPlatform/komodo-defi-framework/blob/main/mm2src/mm2_main/src/lp_ordermatch/simple_market_maker.rs#L41
 
Most likely, mm2  komodo-defi-framework code base has a rounding assumption that any price below certain smaller value will be truncated to zero. 

Hopefully this source code limitation bug can be fixed and allow Cheetahcoin Nengcoin etc smaller coins have a pricing in Komodo wallet.  Currently AtomicDEX is thinly traded and most user case is for smaller coins with cheap fees.

**Comment by cipig** [comment]
the integrated maker bot needs a price source... it uses the URL you passed to it... eg https://prices.komodo.earth/api/v2/tickers ... if CHTA does not have a price there, i expect to see the above error... CHTA has a id for coinpaprika and livecoinwatch defined in https://github.com/KomodoPlatform/coins/tree/master/api_ids ... coinpaprika can't be used though, because CHTA is missing circulating supply info there and as such does not have a market cap... but paprika only shows the prices of the top 2500 coins in their free API... without a mcap a coin has no ranking and as such can't be in top 2500... update the supply on paprika, so CHTA has a chance to be in top 2500 coins, then the chance is higher that there will be a price for it

**Comment by smk762** [comment]
No longer appears to be an issue 
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/35845239/f73dcdb7-5a9b-48d8-ba41-dc8bb44095c3)

**Comment by cipig** [comment]
that is only because the price of CHTA surpassed 0.00001... everything below is shown as 0
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/32116761/a214ac70-46f5-4895-9b18-e215d8144b4b)

price of BTTC is 0.00000160 $, CHTA is 0.00000398 $... both show up as 0...so looks like the app cuts off the last 3 decimals, so it gets the price with 8 decimals from the API, but somewhere in code it's stripped down to 5 decimals.
