### ISSUE TITLE
[BUG]: BCH trading pairs do not work

### ISSUE THREAD

**Issue by johncenaaaaaaa** [KomodoPlatform/komodo-wallet-desktop#2411]
Any idea why this BCH-DAI(AVAX-20) does not want to work? Why can't I place that limit order? Other trading pairs I've tried that don't want to work either: BCH-ETH, BCH-AVAX and their derivative tokens. Trading pairs that work: BCH-LTC, BCH-BTC.

Also is this even the right place to file a bug report? I were unable to find any information inside the app itself or the website as to what the right bug reporting procedure is.
![Screenshot from 2024-02-27 19-37-34](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/161508555/9639915f-bd79-45c4-9577-d5263f4b5472)

https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/161508555/37620cd3-f29c-4c97-a57d-576c7ab8101d

**Comment by cipig** [comment]
In order to place AVX20 orders, you need AVAX balance (for the txfees). Same with ERC20... you need ETH. And for BEP20 you need BNB... and so on. You can try to get some here: https://dexstats.info/gas.php

**Comment by johncenaaaaaaa** [comment]
All right! Thank you very much for your help. I have had no idea it works this way. There should be some warning/information for that saying something like: You can't place the order because you have no AVX20 to pay for the exchange process fees.

I wonder though why the fees cause problem with ETH, AVAX and alike but not with bitcoin, litecoin and alike. What's so different about their design.

**Comment by cipig** [comment]
Only EVM (Ethereum Virtual Machine) chains have this fee system, normal coins like BTC, LTC, KMD not.
The design is completely different... on EVM chains every token runs on the same chain, that's why those chains are often congested and fees are high. Normal coins run on their own chain, one coin = one chain, not 1 million tokens on same chain.

**Comment by johncenaaaaaaa** [comment]
That makes sense. Thank you once more, friend.
