### ISSUE TITLE
Live Coin Watch graph hyperlink is not usable

### ISSUE THREAD

**Issue by AndrewDelaney** [KomodoPlatform/komodo-wallet-desktop#2418]
On the DEX tab there is a Live Coin Watch graph widget that contains a hyperlink to the specific coin on the website.
There are a couple issues around this link:
- This link can only be clicked using **CTRL + Click** or **SHIFT + Click**
- Once clicked, it opens the website in the graph window within the app
- The website does not fit nicely within this window
- The website is partially blocked by a popup to accept cookies which cannot be closed as the accept button cannot be clicked
- None of the links on the website can be clicked
- There is no was to open this link in browser other than right clicking on the link and selecting "Copy link address" in the context menu

See attached video for demonstration:

https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/30876243/22ac7fef-5aa6-41c0-b24f-37f80c4e5135

**Comment by smk762** [comment]
Nice find! We should be able to force this to open a new browser tab instead.
