### ISSUE TITLE
[BUG]: Unable to send the feedback from the WebAPP, "ERR_CERT_DATE_INVALID' error is displayed at the Console tab of Developer window.

### ISSUE THREAD

**Issue by ShantanuSharma9873** [KomodoPlatform/komodo-wallet-desktop#2429]
**Summary**
It is observed that the '**Something Wrong :( Please try again later. Your feedback is very important for us.**' error message is displayed on sending the feedback. 

**To Reproduce**
1. Go to '**Komodo Platform**'
2. Move to the '**Feedback**' tab from the '**Settings**' menu.
3. Enter the valid '**Email id**' and the comments in the '**Feedback**' text box and then click on '**Send Feedback**' button.
4. See the error message displayed below.  

**Expected behavior**
The user should be able to send the feedback successfully in both Login & Logout status. 

**Operating Environment(s):**
 - OS: [Windows ]
 - Komodo Wallet Version: [ 0.7.2]
 - Build branch: [Prod] 

**Additional context**
- 'webform/' API request getting failed 
- POST https://komodo.earth:8181/webform/ net::ERR_CERT_DATE_INVALID

https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/167987768/d2f8741a-4400-40cc-ab4b-80bf1372ba89

**Comment by smk762** [comment]
Thanks, I'll check this

**Comment by ShantanuSharma9873** [comment]
Issue Resolved. Thanks !
