### ISSUE TITLE
[FEATURE REQUEST]: Liquidity view / Multi order view (open discussion)

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/komodo-wallet-desktop#943]
**Is your feature request related to a problem? Please describe.**

We removed the multi-order view during the refactor of the trading pro page, now we can do something a little more evolve.

Since, atomicdex api has the possibility to update maker orders, so we can define a spread choose an asset for liquidity for example KMD, and have an automatic update of maker orders.

**Describe the solution you'd like**
- Bob want to give liquidity for 500 KMD
- Bob want to trade his KMD against stablecoin (USDT, BUSD, USDC, DAI) and premium coins (QTUM, LTC, BCH)
- The software verify if Bob have BNB enabled (and balance > 0 for fees) for stablecoin, and will also enable coins that he selected 
- The software will create a trading configuration with Bob Settings, and placed the initial order based on the current price and spread
- Every 30 seconds the update maker order service will update every orders based on the settings from Bob
- Each time Bob open the trading view, his orders will be updated

**Describe alternatives you've considered**

**Additional context**

**Comment by tonymorony** [comment]
I do propose to add `Single/Multi` switch similar to this one:

![image](https://user-images.githubusercontent.com/24797699/120887301-34abf280-c61c-11eb-9718-d45fdc187785.png)

somewhere on top of this widget:

<img width="292" alt="Screenshot 2021-06-05 at 16 36 57" src="https://user-images.githubusercontent.com/24797699/120887321-4c837680-c61c-11eb-9b6e-fafc2d349652.png">

and place order multi-order version similar to the mobile one (with auto-filling on USD price input and etc):

![image](https://user-images.githubusercontent.com/24797699/120887363-85bbe680-c61c-11eb-97c1-f3c9d344b087.png)

after we return that we can move forward with orders auto-balancing

**Comment by smk762** [comment]
Closing as stale. Will reconsider this feature in future
