### ISSUE TITLE
[FEATURE REQUEST]: Add "FillOrKill" or "GoodUntilCancelled" options when placing order

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet-desktop#956]
1) If the user wants to match the selected order from the orderbook GUI should use `FillOrKill` flag by default to not create maker order if not matched in case if converting to Maker order is not selected

Selector:
![image](https://user-images.githubusercontent.com/24797699/120888323-e4379380-c621-11eb-8c36-415958d40461.png)

2) If user creating maker order `setprice` needs to be used (instant order placing without match attempt) with minvolume param (cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/553) :

![image](https://user-images.githubusercontent.com/24797699/120888372-2d87e300-c622-11eb-8c75-605811fb6aed.png)

**Comment by Milerius** [comment]
Hello @tonymorony, the simple trading view already use FillOrKill by default, and we plan to let the user choose the mode of the order in the pro view in the future, please check as an example: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/889/commits/7ea70847aa08abccf108fd8233a0dd8b382c15b0

**Comment by Milerius** [comment]
<img width="822" alt="Capture d’écran 2021-06-06 à 07 52 00" src="https://user-images.githubusercontent.com/21139416/120914097-1554aa00-c69c-11eb-808e-60e28c1539e3.png">

^was thinking about such a solution for pro view

**Comment by tonymorony** [comment]
> Hello @tonymorony, the simple trading view already use FillOrKill by default, and we plan to let the user choose the mode of the order in the pro view in the future, please check as an example: [7ea7084](https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/7ea70847aa08abccf108fd8233a0dd8b382c15b0)
> 
> Pro view will keep `GoodTilCancelled` by default, but will propose to choose your order_type with a combobox

Great, thanks for insights! let's focus together explicitly on trading logic/experience improvement in the next split to make it crystal clear since it's essential features of the DEX part

**Comment by Milerius** [comment]
Implemented, simple view use FillOrKill by default, and Pro view GoodTilCancelled !

**Comment by Milerius** [comment]
^ feel free to re-open the issue if you have another idea in mind

**Comment by tonymorony** [comment]
Still think we shouldn't convert not matched orders to maker ones by default and use "FillOrKill" with "GoodTillCancelled" as an activable option.

Also if you explicitly creating a maker order "setprice" needs to be used without 30 seconds of waiting imo
